// Package site renders the board as plain static files: a feed page that
// filters a JSON index in the browser, one page per vacancy, a status page.
// No server, no database: any static host (GitHub Pages) serves it for free.
package site

import (
	"bytes"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"html/template"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/Beknur1003/gojobs/internal/models"
)

//go:embed templates/*.html assets/*
var files embed.FS

var jsonMarshal = json.Marshal

// marker is written into every output dir. The builder only ever deletes a
// directory that carries it, so a typo in config cannot wipe the wrong folder.
const marker = ".gojobs-build"

type Config struct {
	Title    string
	BaseURL  string // absolute, no trailing slash
	BasePath string // "/gojobs" or ""
	Repo     string
	FeedDays int
	OutDir   string
}

type Builder struct {
	cfg  Config
	tmpl *template.Template
	now  func() time.Time
}

func New(cfg Config) (*Builder, error) {
	b := &Builder{cfg: cfg, now: time.Now}
	tmpl, err := template.New("").Funcs(b.funcs()).ParseFS(files, "templates/*.html")
	if err != nil {
		return nil, fmt.Errorf("site.New: %w", err)
	}
	b.tmpl = tmpl
	return b, nil
}

// BoardsSummary is the state of company-board discovery, for the about page.
type BoardsSummary struct {
	Checked int // boards probed at least once
	Active  int // boards with Go roles at their last check
}

type Result struct {
	Feed  int // jobs in the feed
	Pages int // vacancy pages written
}

// Build renders everything into a fresh directory and swaps it in at the end,
// so a failed build leaves the previous site untouched.
func (b *Builder) Build(jobs []models.Job, feeds map[string]models.FeedStatus, boards BoardsSummary, updated time.Time) (Result, error) {
	out := filepath.Clean(b.cfg.OutDir)
	if err := checkOutDir(out); err != nil {
		return Result{}, err
	}
	tmp := out + ".new"
	if err := os.RemoveAll(tmp); err != nil {
		return Result{}, fmt.Errorf("site.Build: %w", err)
	}

	feed, pages := b.split(jobs)
	page := b.basePage(updated, len(feed))

	w := writer{root: tmp}
	w.file(marker, []byte("generated by gojobs; this directory is replaced on every build\n"))
	w.file(".nojekyll", nil) // GitHub Pages: serve files as they are
	w.copyAssets()

	w.render(b.tmpl, "index.html", "index.html", indexPage{basePage: page, Jobs: cardsOf(feed, 30), Total: len(feed), Stats: statsOf(feed)})
	main, companies := feedRows(feeds)
	w.render(b.tmpl, "about/index.html", "about.html", aboutPage{basePage: page, Feeds: main, Companies: companies, Boards: boards})
	w.render(b.tmpl, "404.html", "404.html", page)
	// Vacancy pages carry no build date, so a daily rebuild leaves the
	// thousands of pages that did not change byte-identical.
	stable := page
	stable.Updated = time.Time{}
	for _, j := range pages {
		w.render(b.tmpl, "jobs/"+j.Slug+"/index.html", "job.html", jobPage{basePage: stable, Job: viewOf(j), InFeed: inFeed(j, feed)})
	}
	w.json("data/jobs.json", feedJSON{Updated: updated, Jobs: cardsOf(feed, len(feed))})
	w.file("sitemap.xml", b.sitemap(feed))
	w.file("feed.xml", b.rss(feed, updated))
	w.file("robots.txt", []byte("User-agent: *\nAllow: /\nSitemap: "+b.cfg.BaseURL+"/sitemap.xml\n"))
	if w.err != nil {
		return Result{}, fmt.Errorf("site.Build: %w", w.err)
	}

	if err := swap(tmp, out); err != nil {
		return Result{}, fmt.Errorf("site.Build: %w", err)
	}
	return Result{Feed: len(feed), Pages: len(pages)}, nil
}

// split returns the feed (open, newest first) and all pages to write. A post
// in a channel stays in the feed for FeedDays; a listing on a company or job
// board stays as long as the board still shows it, however old it is.
func (b *Builder) split(jobs []models.Job) (feed, pages []models.Job) {
	cutoff := b.now().Add(-time.Duration(b.cfg.FeedDays) * 24 * time.Hour)
	pages = append(pages, jobs...)
	sort.SliceStable(pages, func(i, k int) bool { return pages[i].PostedAt.After(pages[k].PostedAt) })
	now := b.now()
	for _, j := range pages {
		if !j.Closed && (j.PostedAt.After(cutoff) || listed(j, now)) {
			feed = append(feed, j)
		}
	}
	return feed, pages
}

// listedWithin is how fresh a board's confirmation must be. Boards with Go
// roles are read daily, so three days covers a missed run or two.
const listedWithin = 72 * time.Hour

// listed reports a job that a board confirmed recently.
func listed(j models.Job, now time.Time) bool {
	for _, s := range j.Sources {
		if s.Listing() && now.Sub(s.LastSeen) < listedWithin {
			return true
		}
	}
	return false
}

func inFeed(j models.Job, feed []models.Job) bool {
	for _, f := range feed {
		if f.ID == j.ID {
			return true
		}
	}
	return false
}

func checkOutDir(out string) error {
	if out == "." || out == "" || filepath.IsAbs(out) || strings.HasPrefix(out, "..") {
		return fmt.Errorf("site.Build: output dir %q must be a subdirectory of the project", out)
	}
	entries, err := os.ReadDir(out)
	if errors.Is(err, os.ErrNotExist) || len(entries) == 0 {
		return nil
	}
	if err != nil {
		return fmt.Errorf("site.Build: %w", err)
	}
	if _, err := os.Stat(filepath.Join(out, marker)); err != nil {
		return fmt.Errorf("site.Build: %s exists and was not made by gojobs (no %s); refusing to replace it", out, marker)
	}
	return nil
}

func swap(tmp, out string) error {
	old := out + ".old"
	if err := os.RemoveAll(old); err != nil {
		return err
	}
	if _, err := os.Stat(out); err == nil {
		if err := os.Rename(out, old); err != nil {
			return err
		}
	}
	if err := os.Rename(tmp, out); err != nil {
		return err
	}
	return os.RemoveAll(old)
}

// writer collects the first error so Build reads as a list of outputs.
type writer struct {
	root string
	err  error
}

func (w *writer) file(rel string, data []byte) {
	if w.err != nil {
		return
	}
	p := filepath.Join(w.root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		w.err = err
		return
	}
	w.err = os.WriteFile(p, data, 0o644)
}

func (w *writer) render(t *template.Template, rel, name string, data any) {
	if w.err != nil {
		return
	}
	var buf bytes.Buffer
	if err := t.ExecuteTemplate(&buf, name, data); err != nil {
		w.err = fmt.Errorf("render %s: %w", rel, err)
		return
	}
	w.file(rel, buf.Bytes())
}

func (w *writer) json(rel string, v any) {
	if w.err != nil {
		return
	}
	raw, err := json.Marshal(v)
	if err != nil {
		w.err = err
		return
	}
	w.file(rel, raw)
}

func (w *writer) copyAssets() {
	if w.err != nil {
		return
	}
	w.err = fs.WalkDir(files, "assets", func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		data, err := files.ReadFile(p)
		if err != nil {
			return err
		}
		w.file(p, data)
		return w.err
	})
}
